# Generated by Django 4.2.11 on 2025-05-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="PosterUrl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
